name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform-destroy-plan:
    name: Terraform Destroy Plan
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config=${{ github.event.inputs.environment }}.backend.tfvars

      - name: Terraform Destroy Plan
        run: terraform plan -destroy --var-file="${{ github.event.inputs.environment }}.tfvars" -out=tfdestroyplan

      - name: Upload Destroy Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfdestroyplan
          path: terraform/tfdestroyplan
          retention-days: 1

  terraform-destroy-apply:
    name: Terraform Destroy Apply
    runs-on: ubuntu-latest
    needs: terraform-destroy-plan
    environment: ${{ github.event.inputs.environment }}-apply

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config=${{ github.event.inputs.environment }}.backend.tfvars

      - name: Download Destroy Plan
        uses: actions/download-artifact@v4
        with:
          name: tfdestroyplan
          path: terraform/

      - name: Terraform Destroy
        run: terraform apply -auto-approve tfdestroyplan
